version: '3'

services:
  munge_data:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        UBUNTU_VERSION: $UBUNTU_VERSION
    environment:
      PYENV_VERSION: $PYTHON_VERSION
    env_file: .env.local
    volumes:
      - .:/usr/src/app
    command: >
      bash -i -c "python munge.py"
  db:
    image: postgres:$POSTGRES_VERSION
    volumes:
      - ./data:/usr/data:ro
      - ./data_load.sql:/docker-entrypoint-initdb.d/data_load.sql:ro
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analysis
      PGDATA: /var/lib/postgresql/data/pgdata
  jupyter-analysis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        UBUNTU_VERSION: $UBUNTU_VERSION
    env_file: .env.local
    environment:
      PYENV_VERSION: $PYTHON_VERSION
    volumes:
      - .:/usr/src/app
    ports:
      - "8889:8888"
    depends_on:
      - db
    command: >
      bash -i -c "poetry run jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
