version: '3'

services:
  db:
    image: postgres:$POSTGRES_VERSION
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analysis
      PGDATA: /var/lib/postgresql/data/pgdata
  jupyter-analysis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        python_version: $PYTHON_VERSION
        ubuntu_version: $UBUNTU_VERSION
    env_file: .env.local
    volumes:
      - .:/usr/src/app
    ports:
      - "8889:8888"
    depends_on:
      - db
    command: >
      bash -c "
      export PYENV_ROOT=\"/root/.pyenv\"
      && export PATH=\"$$PYENV_ROOT/bin:$$PATH\"
      && eval \"$$(pyenv init -)\"
      && eval \"$$(pyenv virtualenv-init -)\"
      && pyenv activate current
      && jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
